---
  - name: copy tarball to host
    copy:
      src: /tmp/nginx_v1_0.tar
      dest: /tmp/nginx_v1_0.tar

  - name: load container from tarball
    docker_image:
      name: nginx:v1.0
      load_path: /tmp/nginx_v1_0.tar
      timeout: 120
      state: present
      source: load


