---
  -
    name: create build directory
    file:
      path: /tmp/demo-nginx
      state: directory
      owner: root
      group: root
      mode: '0755'

  -
    name: copy Dockerfile
    copy:
      src: ./
      dest: /tmp/demo-nginx
      owner: root
      group: root
      mode: '0644'

  - name: build container image
    docker_image:
      name: nginx:v1.0
      build:
        path: /tmp/demo-nginx
      source: build
      state: present

  - name: archive container image as a tarball
    docker_image:
      name: democontainer:v1.0
      archive_path: /tmp/nginx_v1_0.tar
      timeout: 120
      source: pull
      state: present





