---
  - name: Nginx create build directory
    file:
      path: /tmp/demonginx
      state: directory
      owner: root
      group: root
      mode: '0755'

  - name: Nginx copy Dockerfile
    copy:
      src: ./nginx_app/
      dest: /tmp/demonginx/
      owner: root
      group: root
      mode: '0644'


  - name: Nginx build container image
    docker_image:
      name: nginx:v1.0
      build:
        path: /tmp/demonginx
      source: build
      pull: yes
      state: present

  - name: Nginx archive container image as a tarball
    docker_image:
      name: nginx:v1.0
      archive_path: /tmp/nginx_v1_0.tar
      source: pull
      state: present

