---
-
  gather_facts: false
  hosts: monitor
  roles:
    - app_build
-
  gather_facts: false
  hosts: blue_green
  roles:
    - app_deploy
-
  gather_facts: false
  hosts: monitor
  roles:
    - app_deploy